config/routes.rb
InstaFurniture::Application.routes.draw do
  get 'sessions/create'

  resources :listings
  # map '/' to be a redirect to '/listings'
  root :to => redirect('/listings')
  # user login
  resources :users

  get 'auth/:provider/callback' => 'sessions#create', :as => 'login'
  get '/mock_login' => 'sessions#create_mock', :as => 'mock_login'
  get '/mock_login/:uid' => 'sessions#create_mock', :as => 'mock_login_with_uid'
  get '/logout' => 'sessions#logout', :as => 'logout'
  get 'auth/failure' => 'sessions#error', :as => 'login_fail'
end

app/models/listing.rb
class Listing < ActiveRecord::Base
    has_one_attached :photo
    # attr_accessor :title, :price, :label, :post_date
end

app/models/user.rb
class User < ActiveRecord::Base
  # attr_accessor :title, :price, :label, :post_date
  def self.from_omniauth(auth)
    User.find_or_create_by!(uid: auth[:uid]) do |u|
      u.provider = auth[:provider]
      u.uid = auth[:uid]
      u.oauth_token = auth[:credentials][:token]
      u.oauth_expires_at = Time.at(auth[:credentials][:expires_at])
      u.email = auth[:info][:email]
      u.first_name = auth[:info][:first_name]
      u.last_name = auth[:info][:last_name]
      u.profile_pic = auth[:info][:image]
    end
  end

  def self.get_user_info(uid)
    # Active Record will take care of building the query to avoid injection attacks
    user = User.where(uid: uid).first
    if user.nil?
      nil
    else
      {
        :uid => user[:uid],
        :email => user[:email],
        :first_name => user[:first_name],
        :last_name => user[:last_name],
        :profile_pic => user[:profile_pic]
      }
    end
  end

  def self.get_email(uid)
    user = User.where(uid: uid).first
    if user.nil?
      nil
    end
    user[:email]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  def get_user_info
    if session.has_key?(:uid)
      # User logged in
      uid = session[:uid]
      User.get_user_info(uid)
    else
      # User not logged in
      nil
    end
  end

  def show
    @user = get_user_info
    if @user.nil?
      flash[:notice] = 'Please log in with columbia.edu email'
      redirect_to "/users"
      return
    end
    id = params[:id] # retrieve listing ID from URI route
    @listing = Listing.find(id) # look up listing by unique ID
    @owner_email = User.get_email(@listing[:uid])
    @owns_listing = @listing[:uid] == @user[:uid]
    # will render app/views/Listings/show.<extension> by default
  end

  def index
    @user = get_user_info
    if @user.nil?
      flash[:notice] = 'Please log in with columbia.edu email'
      redirect_to "/users"
      return
    end
    @listings = Listing.all
    @last_query = {
      :pickup => true,
      :deliver => true,
      :elevator => false
    }

    # Preference pickup / deliver
    unless params.has_key?('filter_pick_up') && params.has_key?('filter_deliver')
      if params.has_key?('filter_pick_up') # Pick up only
        @listings = @listings.where(pickup_only: true)
        @last_query[:pickup] = true
        @last_query[:deliver] = false
      elsif params.has_key?('filter_deliver')
        @listings = @listings.where.not(pickup_only: true)
        @last_query[:pickup] = false
        @last_query[:deliver] = true
      end
    end

    # Elevator building
    if params.has_key?('filter_elevator')
      @listings = @listings.where(elevator_building: true)
      @last_query[:elevator] = true
    end

    @show_my_listings = false
    # My listings
    if params.has_key?('filter_my_listings')
      @listings = @listings.where(uid: @user[:uid])
      @show_my_listings = true
    end

    # Search keyword
    if params.has_key?('query') && !params[:query].blank?
      input = params[:query]
      @last_query[:search] = input
      search_words = input.split(' ')
      result = []

      search_words.each do |word|
        result.concat(@listings.where("LOWER(name) LIKE ?", "%#{word.downcase}%").to_a)
      end
      @listings = result
    end

    @no_results = @listings.empty?

  end

  def new
    @user = get_user_info
    if @user.nil?
      flash[:notice] = 'Please log in with columbia.edu email'
      redirect_to "/users"
      return
    end
    # default: render 'new' template
  end

  def create
    @user = get_user_info
    if @user.nil?
      flash[:notice] = 'Please log in with columbia.edu email'
      redirect_to "/users"
      return
    end
    new_listing_info = listing_params
    new_listing_info[:uid] = @user[:uid]
    @listing = Listing.create!(new_listing_info)
    flash[:success] = "#{@listing.name} was successfully created."
    redirect_to listings_path
  end

  def edit
    @user = get_user_info
    if @user.nil?
      flash[:notice] = 'Please log in with columbia.edu email'
      redirect_to "/users"
      return
    end
    @listing = Listing.find params[:id]
    if @listing[:uid] != @user[:uid]
      flash[:notice] = "Error: You are not allowed to edit someone else's listing!"
      redirect_to listings_path
    end
  end

  def update
    @user = get_user_info
    if @user.nil?
      flash[:notice] = 'Please log in with columbia.edu email'
      redirect_to "/users"
      return
    end
    @listing = Listing.find params[:id]
    if @listing[:uid] != @user[:uid]
      flash[:notice] = "Error: You are not allowed to edit someone else's listing!"
      redirect_to listings_path
      return
    end
    @listing.update_attributes!(listing_params)
    flash[:success] = "#{@listing.name} was successfully updated."
    redirect_to listing_path(@listing)
  end

  def destroy
    @user = get_user_info
    if @user.nil?
      flash[:notice] = 'Please log in with columbia.edu email'
      redirect_to "/users"
      return
    end
    @listing = Listing.find(params[:id])
    if @listing[:uid] != @user[:uid]
      flash[:notice] = "Error: You are not allowed to delete someone else's listing!"
      redirect_to listings_path
      return
    end
    @listing.destroy
    flash[:success] = "Listing '#{@listing.name}' deleted."
    redirect_to listings_path
  end

  private

  def listing_params
    # https://api.rubyonrails.org/v6.1.4/classes/ActionController/StrongParameters.html
    params.require(:listing).permit(:name, :description, :elevator_building, :pickup_only, :purchase_date, :photo,
                                    :location, :uid, :email, :phone, :price)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    # Real user login
    auth = request.env['omniauth.auth']

    # Restrict to @columbia.edu, @*.columbia.edu, @barnard.edu, @*.barnard.edu
    email_domain = auth[:info][:email].split("@").last
    if !/^(.+\.)*columbia.edu$/i.match(email_domain) && !/^(.+\.)*barnard.edu$/i.match(email_domain)
      flash[:notice] = "Login failed: @#{email_domain} is not a valid Columbia email. InstaFurniture only accepts Columbia users."
      redirect_to '/users'
      return
    end

    User.from_omniauth(auth)
    session['uid'] = auth[:uid]
    redirect_to root_path
  end

  def create_mock
    # Mock user login in test
    # TODO: Make sure only test frameworks can do this
    if params.has_key?(:uid)
      session['uid'] = params[:uid]
      redirect_to root_path
      return
    end
    auth = {
      :provider => 'google_oauth2',
      :uid => '116978184920182545388',
      :credentials => {
        :token => 'ya29.a0ARrdaM-p0Kb9_VsGomy-TtHrT7UEl5CoLhJqw1NQ3sA3BbxgGTN1zDoamV80sqxxpHQs-yGCEWPxib4op0VdpOA3a2A6M370VN6nwGNOlQ12jMuWUHVjX9k8SL-tLQvMf1fz0CRg_sI74Inls-4TcoYXXBXm',
        :expires_at => 1637213872
      },
      :info => {
        :email => 'mz2866@columbia.edu',
        :first_name => 'Scott',
        :last_name => 'Zhao',
        :image => 'https://lh3.googleusercontent.com/a-/AOh14GjXlewpIKCuS-1Sx57C0r-Z5oDMEVqgsbfklSnz=s96-c'
      }
    }
    User.from_omniauth(auth)
    session['uid'] = '116978184920182545388'
    redirect_to root_path
  end

  def logout
    if session.has_key?(:uid)
      session.delete(:uid)
    end
    redirect_to '/users'
    flash[:success] = 'Successfully logged out'
  end

  def error
    flash[:notice] = "Login failed: #{params[:message]}"
    redirect_to '/users'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index

	end
end

app/helpers/movies_helper.rb
module MoviesHelper
  # Checks if a number is odd:
  def oddness(count)
    count.odd? ?  "odd" :  "even"
  end
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %script{:src => "https://code.jquery.com/jquery-2.1.3.min.js"}
    %script{:src => "https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"}
    %link(rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous")
    %link(rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.0.3/css/font-awesome.css")
    %title InstaFurniture
    = stylesheet_link_tag 'application', 'media' => 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    :css
      @import url('https://fonts.googleapis.com/css2?family=Manrope:wght@200;300;400;500;600;700;800&display=swap');

  %body
    %div.container-fullwidth
      %nav.navbar.navbar-expand-lg.navbar-dark.bg-logo.mb-4
        %a.navbar-brand{:href => listings_path}
          = image_tag("logo.svg", size: "150x50")
        - if @user
          %button.navbar-toggler.collapsed{"aria-controls" => "navbarColor02", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarColor02", "data-toggle" => "collapse", :type => "button"}
            %span.navbar-toggler-icon
          #navbarColor02.navbar-collapse.collapse{:style => ""}
            %ul.navbar-nav
              %li.nav-item{:id => "navbar-listing"}
                %a.nav-link{:href => listings_path} Listings
              %li.nav-item{:id => "navbar-add"}
                %a.nav-link{:href => new_listing_path} Add Listing
              %li.nav-item.mr-3{:id => "navbar-my"}
                %a.nav-link{:href => listings_path(:filter_my_listings => "1")} My Listings
            %ul.navbar-nav.mx-auto
              %li.nav-item
                %form.form-inline{:action => listings_path}
                  = form_tag listings_path, :method => :get do
                    = text_field_tag "query", (@last_query && @last_query[:search] ? "#{@last_query[:search]}" : ""),
                                    class: "form-control mr-sm-2", id: "search-box"
                    %label.form-control.mr-sm-2
                      %input.mr-1{:name => "filter_pick_up", :type => "checkbox", :value => "1",
                                  :checked => (@last_query && !@last_query[:pickup] ? false : true),
                                  id: "checkbox_pick_up"} Pick-up
                    %label.form-control.mr-sm-2
                      %input.mr-1{:name => "filter_deliver", :type => "checkbox", :value => "1",
                                  :checked => (@last_query && !@last_query[:deliver] ? false : true),
                                  id: "checkbox_deliver"} Deliver
                    %label.form-control.mr-sm-2
                      %input.mr-1{:name => "filter_elevator", :type => "checkbox", :value => "1",
                                  :checked => (@last_query && @last_query[:elevator] ? true : false),
                                  id: "checkbox_elevator"} Elevator Building
                    = button_tag type: 'submit', class: "btn btn-outline-light my-2 my-sm-0", id: "button_search" do
                      %i.fa.fa-search
          .d-flex.flex-row-reverse.align-items-center
            .navbar-nav.pull-right.ml-1
              .dropdown
                %a.dropdown-toggle.nav-link.active{"data-toggle" => "dropdown", :href => "#"}
                  Welcome, #{@user[:first_name]} #{@user[:last_name]}
                  %b.caret
                %ul.dropdown-menu
                  %li
                    %a{:href => "logout"}
                      .text-center
                        %i.fa.fa-power-off
                        Logout
            %img.rounded-circle.float-right.shadow{:src => "#{@user[:profile_pic]}", :height => "30px", :width => "30px"}

      #main
        - if flash[:notice]
          %div.alert.alert-danger.text-center
            #notice.message= flash[:notice]
        - elsif flash[:warning]
          %div.alert.alert-danger.text-center
            #warning.message= flash[:warning]
        - elsif flash[:success]
          %div.alert.alert-success.text-center
            #success.message= flash[:success]
        = yield

app/views/listings/edit.html.haml
.row{:align => "center"}
  .col-8.mx-auto{:align => "center", :style => "max-width: 640px;"}
    %h2.mb-4 Edit Listing

    = form_tag listing_path(@listing), :method => :put, multipart: true do
      .row
        .col-sm-4.my-auto.instf-listing-edit-title-left
          = label :listing, :name, 'Name'
        .col-sm-8.my-auto
          = text_field :listing, :name, class: 'form-control'
      %hr
      .row
        .col-sm-4.my-auto.instf-listing-edit-title-left
          = label :listing, :description, 'Description'
        .col-sm-8.my-auto
          = text_field :listing, :description, class: 'form-control'
      %hr
      .row
        .col-sm-4.my-auto.instf-listing-edit-title-left
          = label :listing, :location, 'Location'
        .col-sm-8.my-auto
          = text_field :listing, :location, class: 'form-control'
      %hr
      .row
        .col-sm-4.my-auto.instf-listing-edit-title-left
          = label :listing, :photo, 'Photo'
        .col-sm-8.my-auto{:align => 'left'}
          = file_field :listing, :photo
      %hr
      .row
        .col-sm-4.my-auto.instf-listing-edit-title-left
          = label :listing, :phone, 'Phone Number'
        .col-sm-8.my-auto
          = text_field :listing, :phone, class: 'form-control'
      %hr
      .row
        .col
          .m-auto.instf-listing-edit-title-center
            = label :listing, :price, 'Buyer Pays'
          .m-auto
            .d-flex.flex-row.justify-content-center
              .mr-1.my-auto $
              .ml-0.my-auto
                = text_field :listing, :price, class: 'form-control'
        .col
          .m-auto.instf-listing-edit-title-center
            = label :listing, :purchase_date, 'Purchased On'
          .m-auto
            = date_select :listing, :purchase_date
      %hr
      .row
        .col
          .row-sm-8.mx-auto.instf-listing-edit-title-center
            = label :listing, :elevator_building, 'Building has elevator'
          .row-sm-4.mx-auto
            = check_box :listing, :elevator_building
        .col
          .row-sm-8.mx-auto.instf-listing-edit-title-center
            = label :listing, :pickup_only, 'Buyer must pick up'
          .row-sm-4.mx-auto
            = check_box :listing, :pickup_only

      = submit_tag 'Update Listing', :class => 'btn btn-primary'

app/views/listings/index.html.haml
!!!
%html
  %head
    %script{:src => "https://api.mqcdn.com/sdk/mapquest-js/v1.3.2/mapquest.js"}
    %link{:href => "https://api.mqcdn.com/sdk/mapquest-js/v1.3.2/mapquest.css", :rel => "stylesheet", :type => "text/css"}
    - if @show_my_listings
      :javascript
        document.getElementById("navbar-my").classList.add("active")
    - else
      :javascript
        document.getElementById("navbar-listing").classList.add("active")
  %body
    - if @no_results
      .d-flex.justify-content-center.align-items-center
        .col-auto
          %svg{:height => "100", :space => "preserve", :width => "100", :xmlns => "http://www.w3.org/2000/svg"}
            %path{:d => "M36.087 51.265c-4.84 0-4.84-7.506 0-7.506 4.84.001 4.84 7.506 0 7.506zm27.835-7.505c-4.84 0-4.84 7.506 0 7.506s4.84-7.506 0-7.506zM94.253 50c-.492 23.704-19.78 44.756-44.248 44.248C26.3 93.756 5.249 74.468 5.756 50c.492-23.705 19.78-44.756 44.249-44.248C74.473 6.26 93.745 25.531 94.253 50zm-6.322 0c-.422-20.343-16.928-38.363-37.927-37.927C29.662 12.495 11.642 29.001 12.078 50c.422 20.343 16.928 38.363 37.927 37.927C71.003 87.491 87.496 70.999 87.931 50zM50.005 60.754c-5.137-.277-8.946 4.072-9.625 8.776a3.248 3.248 0 0 0-.094.943c-.018.342.023.644.09.928.666 5.001 4.454 8.512 9.629 8.791 5.479.295 9.447-4.672 9.719-9.719.295-5.479-4.673-9.448-9.719-9.719z"}
        .col-auto
          - if @show_my_listings
            %h2 You have no listings :(
            = link_to 'Create one now!', new_listing_path, :class => 'btn btn-primary'
          - else
            %h2 Too bad! No furniture for you :(
    - else
      .row.m-4
        .col-8
          .container
            .row
              - @listings.each do |listing|
                .col-lg-4.mb-3.d-flex.align-items-stretch
                  %a.card.shadow.clickable-card{:href => "#{listing_path(listing)}", :id => "listing_card_#{listing.id}"}
                    - if listing.photo.attached?
                      %img.card-img-top{:alt => "Card Image", :src => url_for(listing.photo)}/
                    - else
                      %img.card-img-top{:alt => "Card Image", :src => "https://magnolia.com/images/res.cloudinary.com/social-upload-prod-media-cld/image/upload/w_500,f_auto/shopify/1/0207/8508/products/CABT-42A-358_PRM_1_0467d179-1675-46eb-aa71-296adb947ea6.jpg?v=1630695960"}/
                    .card-body.d-flex.flex-column-reverse{:id => "listing#{listing.id}"}
                      .instf-listing-card-price.mt-2 $#{listing.price}
                      .instf-listing-card-title #{listing.name}
        .col-4
          #map.shadow.rounded{:style => "width: 100%; height: 530px;"}
          :javascript
            var items = #{raw @listings.to_json};
            var ids = [];
            var names = [];
            var addresses = [];
            items.forEach(function (item) {
              if (item['location']) {
                ids.push(item['id']);
                names.push(item['name']);
                addresses.push(item['location']);
              }
            })

            window.onload = function() {
              // See README for where to obtain and set up this API key
              L.mapquest.key = "#{ENV["MAPQUEST_APIKEY"]}";

              // Geocode locations, then call the createMap callback
              L.mapquest.geocoding().geocode(addresses, createMap);

              function createMap(error, response) {
                // Initialize the Map
                var map = L.mapquest.map('map', {
                  layers: L.mapquest.tileLayer('map'),
                  center: [0, 0],
                  zoom: 12
                });

                // Generate the feature group containing markers from the geocoded locations
                var featureGroup = generateMarkersFeatureGroup(response);

                // Add markers to the map and zoom to the features
                featureGroup.addTo(map);
                map.fitBounds(featureGroup.getBounds());
              }

              function generateMarkersFeatureGroup(response) {
                var group = [];
                for (var i = 0; i < response.results.length; i++) {
                  var location = response.results[i].locations[0];
                  var locationLatLng = location.latLng;
                  var associatedListingID = ids[i];
                  // Create a marker for each location
                  // var marker = L.marker(locationLatLng, {icon: L.mapquest.icons.marker()})
                  //   .bindPopup(location.adminArea5 + ', ' + location.adminArea3);
                  // https://stackoverflow.com/questions/50151688/marker-events-for-mapquest
                  var marker = L.marker(locationLatLng, {icon: L.mapquest.icons.marker()})
                    .bindPopup(`${ids[i]}: ${names[i]}`).on('click', function (e) {
                      var info = e.target._popup._content;
                      var clickedId = info.substring(0, info.indexOf(':'));
                      // Highlight background
                      ids.forEach(function (id) {
                        if (document.getElementById(`listing${id}`).classList.contains('bg-warning') && id !== clickedId) {
                          document.getElementById(`listing${id}`).classList.remove("bg-warning");
                        }
                      })
                      document.getElementById(`listing${clickedId}`).classList.add("bg-warning");
                      });

                  group.push(marker);
                }
                return L.featureGroup(group);
              }
            }

app/views/listings/new.html.haml
:javascript
  document.getElementById("navbar-add").classList.add("active")
.row{:align => "center"}
  .col-8.mx-auto{:align => "center", :style => "max-width: 640px;"}
    %h2.mb-4 Create New Listing

    = form_tag listings_path, multipart: true do
      .row
        .col-sm-4.my-auto.instf-listing-edit-title-left
          = label :listing, :name, 'Name'
        .col-sm-8.my-auto
          = text_field :listing, :name, class: 'form-control'
      %hr
      .row
        .col-sm-4.my-auto.instf-listing-edit-title-left
          = label :listing, :description, 'Description'
        .col-sm-8.my-auto
          = text_field :listing, :description, class: 'form-control'
      %hr
      .row
        .col-sm-4.my-auto.instf-listing-edit-title-left
          = label :listing, :location, 'Location'
        .col-sm-8.my-auto
          = text_field :listing, :location, class: 'form-control'
      %hr
      .row
        .col-sm-4.my-auto.instf-listing-edit-title-left
          = label :listing, :photo, 'Photo'
        .col-sm-8.my-auto{:align => 'left'}
          = file_field :listing, :photo
      %hr
      .row
        .col-sm-4.my-auto.instf-listing-edit-title-left
          = label :listing, :phone, 'Phone Number'
        .col-sm-8.my-auto
          = text_field :listing, :phone, class: 'form-control'
      %hr
      .row
        .col
          .m-auto.instf-listing-edit-title-center
            = label :listing, :price, 'Buyer Pays'
          .m-auto
            .d-flex.flex-row.justify-content-center
              .mr-1.my-auto $
              .ml-0.my-auto
                = text_field :listing, :price, class: 'form-control'
        .col
          .m-auto.instf-listing-edit-title-center
            = label :listing, :purchase_date, 'Purchased On'
          .m-auto
            = date_select :listing, :purchase_date
      %hr
      .row
        .col
          .row-sm-8.mx-auto.instf-listing-edit-title-center
            = label :listing, :elevator_building, 'Building has elevator'
          .row-sm-4.mx-auto
            = check_box :listing, :elevator_building
        .col
          .row-sm-8.mx-auto.instf-listing-edit-title-center
            = label :listing, :pickup_only, 'Buyer must pick up'
          .row-sm-4.mx-auto
            = check_box :listing, :pickup_only
      %hr.mb-4
      .d-flex.flex-row.justify-content-center
        = link_to 'Cancel', listings_path, :class => 'btn btn-primary'
        .mx-2
        = submit_tag 'Create Listing', :class => 'btn btn-primary'

app/views/listings/show.html.haml
!!!
%html
  %head
    %script{:src => "https://api.mqcdn.com/sdk/mapquest-js/v1.3.2/mapquest.js"}
    %link{:href => "https://api.mqcdn.com/sdk/mapquest-js/v1.3.2/mapquest.css", :rel => "stylesheet", :type => "text/css"}
  %body
    .row.mb-4
      .col-8.mx-auto{:align => "center", :style => "max-width: 640px;"}
        .instf-listing-detail-header.mb-2 #{@listing.name}
        %hr
        .d-flex.flex-row.justify-content-between.mb-2
          - if @listing.photo.attached? && @listing.description != ""
            -# Both photo and description
            %img.my-auto.shadow.rounded{:src => (url_for(@listing.photo)), :width => "300px"}
            .mx-2
            .instf-listing-detail-description.my-auto
              #description= @listing.description
          - elsif @listing.photo.attached? && @listing.description == ""
            -# Only photo
            %img.m-auto.shadow.rounded{:src => (url_for(@listing.photo)), :width => "300px"}
          - else
            -# Only description or nothing
            .instf-listing-detail-description.m-auto
              #description= @listing.description
        %hr
        %dl.row
          %dt.col-sm-4.my-auto.instf-listing-detail-title Ask
          %dd.col-sm-8.my-auto.instf-listing-detail-content
            $
            = @listing.price
        %hr
        %dl.row
          %dt.col-sm-4.my-auto.instf-listing-detail-title Location
          %dd.col-sm-8.my-auto.instf-listing-detail-content
            = @listing.location
        %hr
        %dl.row
          %dt.col-sm-4.my-auto.instf-listing-detail-title Purchase Date
          %dd.col-sm-8.my-auto.instf-listing-detail-content
            = @listing.purchase_date.strftime("%B %d, %Y")
        %hr
        %dl.row
          %dt.col-sm-4.my-auto.instf-listing-detail-title Phone
          %dd.col-sm-8.my-auto.instf-listing-detail-content
            = @listing.phone
        %hr
        %dl.row
          %dt.col-sm-4.my-auto.instf-listing-detail-title Email
          %dd.col-sm-8.my-auto.instf-listing-detail-content
            = @owner_email
        %hr
        %dl.row
          %dt.col-sm-4.my-auto.instf-listing-detail-title Elevator
          %dd.col-sm-8.my-auto.instf-listing-detail-content
            - if @listing.elevator_building
              = "Building has elevator"
            - else
              = "No elevator in building"
        %hr
        %dl.row
          %dt.col-sm-4.my-auto.instf-listing-detail-title Pick-up
          %dd.col-sm-8.my-auto.instf-listing-detail-content
            - if @listing.pickup_only
              = "Buyer pick-up only"
            - else
              = "Seller can deliver"
        - if @owns_listing
          = link_to edit_listing_path(@listing), :class => 'btn btn-primary mr-1' do
            .text-center
              %i.fa.fa-edit
              Edit
          = link_to listing_path(@listing), :method => :delete, :class => 'btn btn-primary mr-1' do
            .text-center
              %i.fa.fa-trash-o
              Delete
        - else
          = link_to "sms:#{@listing.phone}", :class => 'btn btn-primary mr-1' do
            .text-center
              %i.fa.fa-comment
              Text
          = link_to "mailto:#{@owner_email}", :class => 'btn btn-primary mr-1' do
            .text-center
              %i.fa.fa-envelope
              Email
        = link_to listings_path, :class => 'btn btn-primary mr-1' do
          .text-center
            %i.fa.fa-home
            Back to listing list

      .col-4.mx-auto.my-auto
        #map.shadow.rounded{:style => "width: 100%; height: 530px;"}
        :javascript
              var addresses = [#{raw @listing.to_json}['location']];
              console.log(addresses);

              window.onload = function() {
                // See README for where to obtain and set up this API key
                L.mapquest.key = "#{ENV["MAPQUEST_APIKEY"]}";

                if(addresses[0]) {
                  // Geocode locations, then call the createMap callback
                  L.mapquest.geocoding().geocode(addresses, createMap);

                  function createMap(error, response) {
                    var location = response.results[0].locations[0];
                    var locationLatLng = location.latLng;
                    // Initialize the Map
                    var map = L.mapquest.map('map', {
                      layers: L.mapquest.tileLayer('map'),
                      center: [locationLatLng["lat"], locationLatLng["lng"]],
                      zoom: 15
                    });

                    // Add markers to map
                    L.marker([locationLatLng["lat"], locationLatLng["lng"]], {
                              icon: L.mapquest.icons.marker(),
                              draggable: false}).addTo(map);
                  }
                }
                else {
                  L.mapquest.map('map', {
                        layers: L.mapquest.tileLayer('map'),
                        center: [40.8075, -73.9626],
                        zoom: 15
                      });
                }
              }

app/views/users/index.html.haml
.row{:align => "center"}
  .col
    = link_to 'Login', '/auth/google_oauth2', :class => 'btn btn-primary'